#!/bin/env bash

################################################################
# SHELL ALIAS
################################################################

alias u0='du --max-depth=0 -h'
alias u1='du --max-depth=1 -h'
alias l='ls -lrth'   # ls is function declared later
alias ll='ls -lh'   # ls is function declared later
alias la='ls -lrtAh' # ls is function declared later
alias l.='find . -maxdepth 1 -name ".*" -ls' # list dotfiles
alias df='df -h'                          # human-readable sizes
alias free='free -mht'                    # show sizes in MB
alias eg='grep -E --colour=always'
alias fgrep='grep -F --colour=always'
alias rsync='rsync -azvhP'
alias navic='navi --cheatsh'
alias m='make'
alias links='find . -maxdepth 1 -type l -ls' # list all links in current folder
# alias c='clear' # can't use <C-l> as it's required for vim-tmux navigation

#### try to prevent accidental data loss
# alias cp='cp -i'
# alias mv='mv -i'

TRASH="${HOME}/.local/share/trash/files/"
mkdir -p "${TRASH}"

alias rm='mv -t "${TRASH}" --backup=numbered -- '
alias nuke_trash='/bin/rm -rf ${TRASH:?}/*'

# cleanup shortcut
alias rout='rm *.out'

alias make='make -s'

# some shells might have 'time' command built-in which is not the standardised one.
alias time='/usr/bin/time'

################################################################
# EDITOR ALIAS
################################################################

alias v='nvim'
alias vnone='nvim -u NONE'
alias nv='nvim'
[ -x "$(command -v nvim)" ] && alias vim='nvim'
# NOTE: uv is also a python virtual env manager.
# alias uv='v +PlugInstall +UpdateRemotePlugins +qa'
alias gv='gvim'
alias vd='vimdiff'
alias gvd='gvimdiff'
alias emacs='emacs & &> /dev/null'
alias suvim='sudo -E gvim'
alias sv='sudo -E vim'
[ -x "$(command -v bat)" ] && alias less='bat'
alias more='less'
alias vb="v \${DOTBASE}/bashrc"
alias sb='source ~/.bashrc'
alias vv='v ~/.vimrc'
alias vc='v ~/.vim/sources/custom_functions.vim'
alias va='v ~/.vim/sources/abbreviations.vim'
alias vs='v ~/.vim/sources/statusline.vim'
alias vp='v ~/.vim/sources/plugins.vim'
alias vba="v \${DOTRC}/bash_aliases"
alias sba="source \${DOTRC}/bash_aliases"
alias vbf="v \${DOTRC}/bash_functions"
alias sbf="source \${DOTRC}/bash_functions"
alias vn='v -u NONE'
alias jupyter-notebook="~/.local/bin/jupyter-notebook --no-browser"


#### WINDOWS
#
alias explorer='/mnt/c/Windows/explorer.exe'

################################################################
# TOOL ALIAS
################################################################

# get timing metrics of curl
alias curltime="curl -w \"@$HOME/.curl_format\" -o /dev/null -s "

# WGET
alias wgold='wget --recursive --timestamping --level=inf --no-remove-listing --convert-links --show-progress --progress=bar:force --no-parent --execute robots=off --verbose --continue --wait=2 --random-wait --reject htm,html,tmp,dstore,db,dll --directory-prefix=guest_dir --regex-type=pcre'
alias wg='wgold --compression=auto'

# GIT
alias dh='git diff --ignore-space-at-eol --ignore-all-space --ignore-space-change --ignore-blank-lines --diff-algorithm=histogram'
alias dhc='git diff --diff-algorithm=histogram --cached'
# alias dhc='git diff --ignore-space-at-eol --ignore-all-space --ignore-space-change --ignore-blank-lines --diff-algorithm=histogram --cached'
alias dhead='dh HEAD'
alias cdr='cd ./"$(git rev-parse --show-cdup)"'
alias gp='git rev-parse --abbrev-ref HEAD | xargs git push origin --set-upstream'
alias gpf='gp --force-with-lease' # --force-if-includes makes you merge changes??
alias gl='git pull'
alias st='git status'
alias br='git branch --format="%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(contents:subject) %(color:green)(%(committerdate:relative)) [%(authorname)]" --sort=-committerdate'
alias log='git log --oneline --no-merges HEAD~20..HEAD'
alias gap='git add -p'
alias gcp='git checkout -p'
alias f='git fetch'
alias groot='cd $(git rev-parse --show-toplevel)'

alias todo='v ${HOME}/todo.md'
alias note='v ${HOME}/note.md'

# PACMAN
alias upe="cat updatelog | xargs -I{} pacman -Qo {} 2>&1 | sed 's/^error:.*owns //g' > noowner && cat noowner | xargs sudo rm -rf"
alias cleanpac='sudo pacman -Rns $(pacman -Qtdq)' # remove unused packages(orphans): if none found o/p :"no targets specified"
alias unlockpac="sudo rm /var/lib/pacman/db.lck" #pacman unlock
# fix typos
alias udpate='sudo pacman -Syyu'
alias upate='sudo pacman -Syyu'
alias updte='sudo pacman -Syyu'
alias updqte='sudo pacman -Syyu'
alias upqll="paru -Syu --noconfirm"
alias upal="paru -Syu --noconfirm"


# PYTHON
alias prp='pipenv run python'
alias psh='pipenv shell'
alias pycalc='python3 -ic "from __future__ import division; from math import *"'

# NETWORK
alias ipshow='ip link show'
alias tux='sudo arpon -d -i wlp3s0 -D'

# FZF
alias of=' fd --follow -j4 --type f --hidden --follow --exclude .git | fzf --header "open file..." --preview "bat -n --color=always {}" --bind "ctrl-/:change-preview-window(down|hidden|)" --preview-window down | xargs nvim'
alias od=' fd --follow -j4 --type d --hidden --follow --exclude .git | fzf --header "open file..." --preview "bat -n --color=always {}" --bind "ctrl-/:change-preview-window(down|hidden|)" --preview-window down | xargs nvim'

# YT-DLP
alias ytlist='yt-dlp --restrict-filename --sub-lang en --playlist-items 139-204 --embed-subs --continue --ignore-errors -f 43 -o "%(autonumber)s - %(title)s.%(ext)s"'

# zoxide
[ -x "$(command -v zoxide)" ] && alias cd='z'

# valgrind
alias vg='valgrind --error-exitcode=1 --tool=memcheck --leak-check=full --errors-for-leak-kinds=definite --show-leak-kinds=definite'
################################################################
#fix obvious typo's
################################################################

# alias cd..='cd ..'
alias pdw="pwd"
alias gti='git'
alias gi='git'
alias sl='ls'

