#!/usr/bin/env bash

function update_ctags {
  ./install_universal_ctags.sh
}

# all commands from 'dotfiles' folder...
pushd $HOME/dotfiles

# if ! git diff-index --quiet HEAD --; then
#     echo "git repo has changes.. subtree won't work.."
#     popd
#     exit 1
# fi

update_ctags

popd

#Misc

# repo no longer contains the fatpack build. use package manager
# curl -Ls 'https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy' >| $HOME/dotfiles/tools/diff-so-fancy
curl -Ls 'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash' >| $HOME/dotfiles/tools/git-completion-bash.sh
