#!/usr/bin/env bash

function update_ctags {
  ./install_universal_ctags.sh
}

# all commands from 'dotfiles' folder...
pushd $HOME/dotfiles

# if ! git diff-index --quiet HEAD --; then
#     echo "git repo has changes.. subtree won't work.."
#     popd
#     exit 1
# fi

update_ctags

popd

#Misc

function update_diff_so_fancy
{
  repo_owner="so-fancy"
  repo_name="diff-so-fancy"

  latest_release_url=$(curl -s "https://api.github.com/repos/${repo_owner}/${repo_name}/releases/latest" | grep -Eo --color=never '"browser_download_url": "[^"]+"' | sed -E 's/.*"([^"]+)"/\1/' | tr -cd '[:graph:]')

  dsh_path="$HOME/dotfiles/tools/diff-so-fancy"

  curl -L "${latest_release_url}" -o "${dsh_path}"
  chmod u+x ${dsh_path}
}

update_diff_so_fancy

curl -Ls 'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash' >| $HOME/dotfiles/tools/git-completion-bash.sh
